### ISSUE TITLE
CSS flash when loading site in Safari on OS X

### ISSUE THREAD

**Issue by davidfstr** [kirbyfan64/kirbyfan64.github.io#2]
See video here: https://www.dropbox.com/s/eu92ih74nunr68s/kirbyfan64-LoadSite.mp4?dl=0

**Comment by kirbyfan64** [comment]
Unfortunately, I'm not sure if there's too much I can do about this. I love [Polymer](https://www.polymer-project.org/1.0/), but it's kind of big, and the fact that I'm using the UI elements too doesn't help. Until the browser downloads the entire imports file, nothing can really be rendered. I also don't have any access to a Mac, so I can't really see what's wrong...

Try this:

- [Open up Safari's web inspector.](https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html)
- Reload the page.
- Screenshot the three sections of the Timelines (*Network Requests*, *Layout and Rendering*, and *JavaScript and Events*) and post them here.

Thanks in advance!

**Comment by davidfstr** [comment]
Yep Polymer is a bit of a giant. :-)

I evaluated it about a year ago for a website I was building and went with Material Design Lite - emphasis on lite - at the time.

I'll get the info you requested late this coming week. Much to do in the next few days.

- David

**Comment by kirbyfan64** [comment]
Yeah... it's gotten better, but it's not "lite".

**Comment by davidfstr** [comment]
Safari screenshots:

* https://www.dropbox.com/s/zpyq0ifffqy0bun/kirbyfan64-Safari-1.png?dl=0
* https://www.dropbox.com/s/8jvxqr292we487k/kirbyfan64-Safari-2.png?dl=0
* https://www.dropbox.com/s/99vp2db6riomrpb/kirbyfan64-Safari-3.png?dl=0

You may also want to try Firefox (47.0.1) since the CSS flash is visible there as well.

**Comment by kirbyfan64** [comment]
Thanks! I'll look into it a bit more later today.

**Comment by kirbyfan64** [comment]
@davidfstr Finally got around to fixing this. Turns out, all I needed to do was mark the pages as `unresolved` to avoid the ugly flashes. Could you try it out in Safari know and see if it works?

**Comment by davidfstr** [comment]
Confirmed that there's no more flash.
